services:
  postgres:
    image: postgres:15-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mock_exam_test
      POSTGRES_USER: mock_exam_test
      POSTGRES_PASSWORD: mockExamPass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mock_exam_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mock_exam_test
      SPRING_DATASOURCE_USERNAME: mock_exam_test
      SPRING_DATASOURCE_PASSWORD: mockExamPass
    networks:
      - mock_exam_net


volumes:
  postgres_data:

networks:
  mock_exam_net:
    driver: bridge