ALTER TABLE teachers
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE experiences
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE educations
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE images
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE user_tokens
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE questions
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE answers
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

ALTER TABLE question_history
    ALTER COLUMN created_date TYPE TIMESTAMP,
    ALTER COLUMN updated_date TYPE TIMESTAMP;

